version: "2"

networks:
  jenkins:
    external: false

volumes:
  jenkins:
    driver: local

services:
  server:
    image: jenkins:latest
    restart: always
    networks:
      - jenkins
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "192.168.1.203:8080:8080"
      - "192.168.1.203:50000:50000"
